theme: jekyll-theme-slate
title: Daniel Feal
description: I am an aerospace engineer and I am studying a Master’s in Big Data, Data Science and AI. The aim of this page is to share my data science projects.
